# [target.x86_64-pc-windows-msvc]
# rustflags = ["-C", "link-arg=/STACK:8000000"]

[build]
rustflags = ["-C", "symbol-mangling-version=v0", "--cfg", "tokio_unstable"]

[target.'cfg(target_os = "windows")']
rustflags = ["--cfg", "windows_slim_errors", "-C", "target-feature=+crt-static"]
