- id: 5ae1c477-37d8-4c92-ade0-52628eafc180
  title: ''
  description: fdsfasdfsd
  status: Todo
  selected_models:
  - provider_id: shouqianba-001
    model_id: gpt-4o-001
    model_name: gpt-4o
    provider_name: 收钱吧
  - provider_id: shouqianba-001
    model_id: gpt-4o-mini-001
    model_name: gpt-4o-mini
    provider_name: 收钱吧
  - provider_id: gemini-001
    model_id: gemini-2-5-pro-exp-001
    model_name: gemini-2.5-pro-exp-03-25
    provider_name: Gemini
  - provider_id: openai-001
    model_id: gpt-4o-mini-official-001
    model_name: gpt-4o-mini
    provider_name: OpenAI
  - provider_id: openai-001
    model_id: gpt-4o-official-001
    model_name: gpt-4o
    provider_name: OpenAI
  selected_tools:
  - provider_id: sqlite-001
    tool_name: execute_query
    provider_name: SQLite数据库服务器
    description: 执行SQL查询
  - provider_id: sqlite-001
    tool_name: get_schema
    provider_name: SQLite数据库服务器
    description: 获取数据库结构
  - provider_id: python-001
    tool_name: execute_python
    provider_name: Python执行服务器
    description: 执行Python代码
  - provider_id: python-001
    tool_name: install_package
    provider_name: Python执行服务器
    description: 安装Python包
  files: []
  recurring_enabled: false
  recurring_pattern: null
  auto_execute: false
  enable_notifications: true
  push_to_feishu: true
  execution_logs: []
  last_execution_result: null
  created_at: 1750326775
  updated_at: 1750326856
  due_date: null
  reminder_date: null
  completed_at: null
- id: 8e6f4cb9-262f-40f0-bbe3-7c87e32483b8
  title: ''
  description: fsdafasdfsda
  status: Todo
  selected_models:
  - provider_id: shouqianba-001
    model_id: gpt-4o-mini-001
    model_name: gpt-4o-mini
    provider_name: 收钱吧
  selected_tools:
  - provider_id: sqlite-001
    tool_name: execute_query
    provider_name: SQLite数据库服务器
    description: 执行SQL查询
  files: []
  recurring_enabled: false
  recurring_pattern: null
  auto_execute: false
  enable_notifications: true
  push_to_feishu: false
  execution_logs: []
  last_execution_result: null
  created_at: 1750326865
  updated_at: 1750326865
  due_date: null
  reminder_date: null
  completed_at: null
